# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ecfdbb67f7fd89761273e9c920b3d382ba00b781805dd338d6da7c5043d5b81eb04e98d82ccc971bd743142387f1324ca76a819f1201d5bafa15c20f998fa7f

test:
  secret_key_base: f3a3fb3bb772e5cd197cba6950978bf689c4b24c2ead3a14e86315286168240d82ad66c0f0f48914f3151ab76ec91789b3a82c3c57c3c656bb2cae970f6359d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
